// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for SubmitBatchRequestTippingWallet.
const (
	SubmitBatchRequestTippingWalletHighloadV2R2 SubmitBatchRequestTippingWallet = "HighloadV2R2"
	SubmitBatchRequestTippingWalletHighloadV3   SubmitBatchRequestTippingWallet = "HighloadV3"
	SubmitBatchRequestTippingWalletV4R2         SubmitBatchRequestTippingWallet = "V4R2"
	SubmitBatchRequestTippingWalletV5R1Final    SubmitBatchRequestTippingWallet = "V5R1Final"
)

// Defines values for SubmitRequestWallet.
const (
	SubmitRequestWalletHighloadV2R2 SubmitRequestWallet = "HighloadV2R2"
	SubmitRequestWalletHighloadV3   SubmitRequestWallet = "HighloadV3"
	SubmitRequestWalletV4R2         SubmitRequestWallet = "V4R2"
	SubmitRequestWalletV5R1Final    SubmitRequestWallet = "V5R1Final"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// SubmitBatchRequest defines model for SubmitBatchRequest.
type SubmitBatchRequest struct {
	// ExpirationTimeSec Expiration time in seconds for the batch landing. If not set, defaults to 18 seconds or time left to the next block time depending on transactions.
	ExpirationTimeSec *int `json:"expiration_time_sec,omitempty"`

	// TippingWallet Sending wallet type for a tipping transaction
	TippingWallet SubmitBatchRequestTippingWallet `json:"tipping_wallet"`

	// Transactions Array of signed TON transactions with wallet types.
	Transactions []struct {
		// Content The signed payload of the TON transaction (in base64).
		Content string `json:"content"`
	} `json:"transactions"`
}

// SubmitBatchRequestTippingWallet Sending wallet type for a tipping transaction
type SubmitBatchRequestTippingWallet string

// SubmitBatchResponse defines model for SubmitBatchResponse.
type SubmitBatchResponse struct {
	// MsgBodyHashes The hashes of the bodies of the external messages passed by the user in the submit batch request
	MsgBodyHashes []string `json:"msg_body_hashes"`
}

// SubmitRequest defines model for SubmitRequest.
type SubmitRequest struct {
	Transaction struct {
		// Content The signed payload of the TON transaction (in base64).
		Content string `json:"content"`
	} `json:"transaction"`

	// UseMevProtection Use MEV protected submission route
	UseMevProtection *bool `json:"use_mev_protection,omitempty"`

	// Wallet Sending wallet type
	Wallet SubmitRequestWallet `json:"wallet"`
}

// SubmitRequestWallet Sending wallet type
type SubmitRequestWallet string

// SubmitResponse defines model for SubmitResponse.
type SubmitResponse struct {
	// MsgBodyHash The hash of the body of the external messsage passed by the user in the submit request
	MsgBodyHash string `json:"msg_body_hash"`
}

// TipWalletRequest defines model for TipWalletRequest.
type TipWalletRequest struct {
	// Address Sender wallet address.
	Address          *string   `json:"address,omitempty"`
	ExternalMessages *[]string `json:"external_messages,omitempty"`
	union            json.RawMessage
}

// TipWalletRequest0 defines model for .
type TipWalletRequest0 = interface{}

// TipWalletRequest1 defines model for .
type TipWalletRequest1 = interface{}

// TipWalletResponse defines model for TipWalletResponse.
type TipWalletResponse struct {
	// Shard Shard id in hex format
	Shard string `json:"shard"`

	// TipWalletAddress Tip wallet address to be used for transaction or bundle submission
	TipWalletAddress string `json:"tip_wallet_address"`
}

// PostApiV2SubmitParams defines parameters for PostApiV2Submit.
type PostApiV2SubmitParams struct {
	// Authorization authorization header
	Authorization string `json:"Authorization"`
}

// PostApiV2SubmitBatchParams defines parameters for PostApiV2SubmitBatch.
type PostApiV2SubmitBatchParams struct {
	// Authorization authorization header
	Authorization string `json:"Authorization"`
}

// GetApiV2TipWalletParams defines parameters for GetApiV2TipWallet.
type GetApiV2TipWalletParams struct {
	// Authorization authorization header
	Authorization string `json:"Authorization"`
}

// PostApiV2TipWalletParams defines parameters for PostApiV2TipWallet.
type PostApiV2TipWalletParams struct {
	// Authorization authorization header
	Authorization string `json:"Authorization"`
}

// PostApiV2SubmitJSONRequestBody defines body for PostApiV2Submit for application/json ContentType.
type PostApiV2SubmitJSONRequestBody = SubmitRequest

// PostApiV2SubmitBatchJSONRequestBody defines body for PostApiV2SubmitBatch for application/json ContentType.
type PostApiV2SubmitBatchJSONRequestBody = SubmitBatchRequest

// PostApiV2TipWalletJSONRequestBody defines body for PostApiV2TipWallet for application/json ContentType.
type PostApiV2TipWalletJSONRequestBody = TipWalletRequest

// AsTipWalletRequest0 returns the union data inside the TipWalletRequest as a TipWalletRequest0
func (t TipWalletRequest) AsTipWalletRequest0() (TipWalletRequest0, error) {
	var body TipWalletRequest0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTipWalletRequest0 overwrites any union data inside the TipWalletRequest as the provided TipWalletRequest0
func (t *TipWalletRequest) FromTipWalletRequest0(v TipWalletRequest0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTipWalletRequest0 performs a merge with any union data inside the TipWalletRequest, using the provided TipWalletRequest0
func (t *TipWalletRequest) MergeTipWalletRequest0(v TipWalletRequest0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTipWalletRequest1 returns the union data inside the TipWalletRequest as a TipWalletRequest1
func (t TipWalletRequest) AsTipWalletRequest1() (TipWalletRequest1, error) {
	var body TipWalletRequest1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTipWalletRequest1 overwrites any union data inside the TipWalletRequest as the provided TipWalletRequest1
func (t *TipWalletRequest) FromTipWalletRequest1(v TipWalletRequest1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTipWalletRequest1 performs a merge with any union data inside the TipWalletRequest, using the provided TipWalletRequest1
func (t *TipWalletRequest) MergeTipWalletRequest1(v TipWalletRequest1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t TipWalletRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Address != nil {
		object["address"], err = json.Marshal(t.Address)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'address': %w", err)
		}
	}

	if t.ExternalMessages != nil {
		object["external_messages"], err = json.Marshal(t.ExternalMessages)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'external_messages': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *TipWalletRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["address"]; found {
		err = json.Unmarshal(raw, &t.Address)
		if err != nil {
			return fmt.Errorf("error reading 'address': %w", err)
		}
	}

	if raw, found := object["external_messages"]; found {
		err = json.Unmarshal(raw, &t.ExternalMessages)
		if err != nil {
			return fmt.Errorf("error reading 'external_messages': %w", err)
		}
	}

	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostApiV2SubmitWithBody request with any body
	PostApiV2SubmitWithBody(ctx context.Context, params *PostApiV2SubmitParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV2Submit(ctx context.Context, params *PostApiV2SubmitParams, body PostApiV2SubmitJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV2SubmitBatchWithBody request with any body
	PostApiV2SubmitBatchWithBody(ctx context.Context, params *PostApiV2SubmitBatchParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV2SubmitBatch(ctx context.Context, params *PostApiV2SubmitBatchParams, body PostApiV2SubmitBatchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV2TipWallet request
	GetApiV2TipWallet(ctx context.Context, params *GetApiV2TipWalletParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV2TipWalletWithBody request with any body
	PostApiV2TipWalletWithBody(ctx context.Context, params *PostApiV2TipWalletParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV2TipWallet(ctx context.Context, params *PostApiV2TipWalletParams, body PostApiV2TipWalletJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostApiV2SubmitWithBody(ctx context.Context, params *PostApiV2SubmitParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV2SubmitRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV2Submit(ctx context.Context, params *PostApiV2SubmitParams, body PostApiV2SubmitJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV2SubmitRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV2SubmitBatchWithBody(ctx context.Context, params *PostApiV2SubmitBatchParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV2SubmitBatchRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV2SubmitBatch(ctx context.Context, params *PostApiV2SubmitBatchParams, body PostApiV2SubmitBatchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV2SubmitBatchRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV2TipWallet(ctx context.Context, params *GetApiV2TipWalletParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV2TipWalletRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV2TipWalletWithBody(ctx context.Context, params *PostApiV2TipWalletParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV2TipWalletRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV2TipWallet(ctx context.Context, params *PostApiV2TipWalletParams, body PostApiV2TipWalletJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV2TipWalletRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostApiV2SubmitRequest calls the generic PostApiV2Submit builder with application/json body
func NewPostApiV2SubmitRequest(server string, params *PostApiV2SubmitParams, body PostApiV2SubmitJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV2SubmitRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostApiV2SubmitRequestWithBody generates requests for PostApiV2Submit with any type of body
func NewPostApiV2SubmitRequestWithBody(server string, params *PostApiV2SubmitParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/submit")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Authorization", runtime.ParamLocationHeader, params.Authorization)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewPostApiV2SubmitBatchRequest calls the generic PostApiV2SubmitBatch builder with application/json body
func NewPostApiV2SubmitBatchRequest(server string, params *PostApiV2SubmitBatchParams, body PostApiV2SubmitBatchJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV2SubmitBatchRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostApiV2SubmitBatchRequestWithBody generates requests for PostApiV2SubmitBatch with any type of body
func NewPostApiV2SubmitBatchRequestWithBody(server string, params *PostApiV2SubmitBatchParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/submit-batch")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Authorization", runtime.ParamLocationHeader, params.Authorization)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewGetApiV2TipWalletRequest generates requests for GetApiV2TipWallet
func NewGetApiV2TipWalletRequest(server string, params *GetApiV2TipWalletParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/tip-wallet")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Authorization", runtime.ParamLocationHeader, params.Authorization)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewPostApiV2TipWalletRequest calls the generic PostApiV2TipWallet builder with application/json body
func NewPostApiV2TipWalletRequest(server string, params *PostApiV2TipWalletParams, body PostApiV2TipWalletJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV2TipWalletRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostApiV2TipWalletRequestWithBody generates requests for PostApiV2TipWallet with any type of body
func NewPostApiV2TipWalletRequestWithBody(server string, params *PostApiV2TipWalletParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/tip-wallet")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Authorization", runtime.ParamLocationHeader, params.Authorization)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostApiV2SubmitWithBodyWithResponse request with any body
	PostApiV2SubmitWithBodyWithResponse(ctx context.Context, params *PostApiV2SubmitParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV2SubmitResponse, error)

	PostApiV2SubmitWithResponse(ctx context.Context, params *PostApiV2SubmitParams, body PostApiV2SubmitJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV2SubmitResponse, error)

	// PostApiV2SubmitBatchWithBodyWithResponse request with any body
	PostApiV2SubmitBatchWithBodyWithResponse(ctx context.Context, params *PostApiV2SubmitBatchParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV2SubmitBatchResponse, error)

	PostApiV2SubmitBatchWithResponse(ctx context.Context, params *PostApiV2SubmitBatchParams, body PostApiV2SubmitBatchJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV2SubmitBatchResponse, error)

	// GetApiV2TipWalletWithResponse request
	GetApiV2TipWalletWithResponse(ctx context.Context, params *GetApiV2TipWalletParams, reqEditors ...RequestEditorFn) (*GetApiV2TipWalletResponse, error)

	// PostApiV2TipWalletWithBodyWithResponse request with any body
	PostApiV2TipWalletWithBodyWithResponse(ctx context.Context, params *PostApiV2TipWalletParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV2TipWalletResponse, error)

	PostApiV2TipWalletWithResponse(ctx context.Context, params *PostApiV2TipWalletParams, body PostApiV2TipWalletJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV2TipWalletResponse, error)
}

type PostApiV2SubmitResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SubmitResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiV2SubmitResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV2SubmitResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiV2SubmitBatchResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SubmitBatchResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiV2SubmitBatchResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV2SubmitBatchResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV2TipWalletResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TipWalletResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetApiV2TipWalletResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV2TipWalletResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiV2TipWalletResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TipWalletResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiV2TipWalletResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV2TipWalletResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostApiV2SubmitWithBodyWithResponse request with arbitrary body returning *PostApiV2SubmitResponse
func (c *ClientWithResponses) PostApiV2SubmitWithBodyWithResponse(ctx context.Context, params *PostApiV2SubmitParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV2SubmitResponse, error) {
	rsp, err := c.PostApiV2SubmitWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV2SubmitResponse(rsp)
}

func (c *ClientWithResponses) PostApiV2SubmitWithResponse(ctx context.Context, params *PostApiV2SubmitParams, body PostApiV2SubmitJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV2SubmitResponse, error) {
	rsp, err := c.PostApiV2Submit(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV2SubmitResponse(rsp)
}

// PostApiV2SubmitBatchWithBodyWithResponse request with arbitrary body returning *PostApiV2SubmitBatchResponse
func (c *ClientWithResponses) PostApiV2SubmitBatchWithBodyWithResponse(ctx context.Context, params *PostApiV2SubmitBatchParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV2SubmitBatchResponse, error) {
	rsp, err := c.PostApiV2SubmitBatchWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV2SubmitBatchResponse(rsp)
}

func (c *ClientWithResponses) PostApiV2SubmitBatchWithResponse(ctx context.Context, params *PostApiV2SubmitBatchParams, body PostApiV2SubmitBatchJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV2SubmitBatchResponse, error) {
	rsp, err := c.PostApiV2SubmitBatch(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV2SubmitBatchResponse(rsp)
}

// GetApiV2TipWalletWithResponse request returning *GetApiV2TipWalletResponse
func (c *ClientWithResponses) GetApiV2TipWalletWithResponse(ctx context.Context, params *GetApiV2TipWalletParams, reqEditors ...RequestEditorFn) (*GetApiV2TipWalletResponse, error) {
	rsp, err := c.GetApiV2TipWallet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV2TipWalletResponse(rsp)
}

// PostApiV2TipWalletWithBodyWithResponse request with arbitrary body returning *PostApiV2TipWalletResponse
func (c *ClientWithResponses) PostApiV2TipWalletWithBodyWithResponse(ctx context.Context, params *PostApiV2TipWalletParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV2TipWalletResponse, error) {
	rsp, err := c.PostApiV2TipWalletWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV2TipWalletResponse(rsp)
}

func (c *ClientWithResponses) PostApiV2TipWalletWithResponse(ctx context.Context, params *PostApiV2TipWalletParams, body PostApiV2TipWalletJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV2TipWalletResponse, error) {
	rsp, err := c.PostApiV2TipWallet(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV2TipWalletResponse(rsp)
}

// ParsePostApiV2SubmitResponse parses an HTTP response from a PostApiV2SubmitWithResponse call
func ParsePostApiV2SubmitResponse(rsp *http.Response) (*PostApiV2SubmitResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV2SubmitResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SubmitResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostApiV2SubmitBatchResponse parses an HTTP response from a PostApiV2SubmitBatchWithResponse call
func ParsePostApiV2SubmitBatchResponse(rsp *http.Response) (*PostApiV2SubmitBatchResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV2SubmitBatchResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SubmitBatchResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiV2TipWalletResponse parses an HTTP response from a GetApiV2TipWalletWithResponse call
func ParseGetApiV2TipWalletResponse(rsp *http.Response) (*GetApiV2TipWalletResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV2TipWalletResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TipWalletResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostApiV2TipWalletResponse parses an HTTP response from a PostApiV2TipWalletWithResponse call
func ParsePostApiV2TipWalletResponse(rsp *http.Response) (*PostApiV2TipWalletResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV2TipWalletResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TipWalletResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
